version: '3'
services:
    adventure-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5005:5005"
            - "8080:8080"
        links:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
            - "27018:27018"
        volumes:
            - "/opt/mongodb:/data/db"
